### ISSUE TITLE
Blank Screen on First Boot

### ISSUE THREAD

**Issue by muhrizkiakbar** [CloverLeafBG/Dell-Latitude-7400-OC-Hackintosh#1]
Hello bro, i have same laptop with you.
i was create installation media and mount EFI partition, and then i paste your EFI into my instalation media,
but i got black screen when trying to install, opencore is loaded but i only get black screen after opencore boot

thanks

**Comment by CloverLeafBG** [comment]
Hello. What's the exact specs of your laptop and what OS you are trying to install? Also review the BIOS settings.

**Comment by Vorboid** [comment]
I've got the same Issue but I'm using your Latitude 7490 guide instead as that's the model I have. I'm trying to install Venture 13.5.2. 
I've attached my log file (using OpenCore 0.88)

Laptop Specs: 
- Intel Core i5 8350U @ 1.7GHz
- 16GB Dual Channel DDR4 RAM
- Intel UHD Graphics 620
- 465GB Samsung SSD 970 Evo Plus

[opencore-2023-09-20-164625.txt](https://github.com/CloverLeafBG/Dell-Latitude-7400-OC-Hackintosh/files/12675188/opencore-2023-09-20-164625.txt)

I appreciate you no longer have your 7490, but any help would be appreciated.

**Comment by CloverLeafBG** [comment]
> I've got the same Issue but I'm using your Latitude 7490 guide instead as that's the model I have. I'm trying to install Venture 13.5.2. I've attached my log file (using OpenCore 0.88)
> 
> Laptop Specs:
> 
> * Intel Core i5 8350U @ 1.7GHz
> * 16GB Dual Channel DDR4 RAM
> * Intel UHD Graphics 620
> * 465GB Samsung SSD 970 Evo Plus
> 
> [opencore-2023-09-20-164625.txt](https://github.com/CloverLeafBG/Dell-Latitude-7400-OC-Hackintosh/files/12675188/opencore-2023-09-20-164625.txt)
> 
> I appreciate you no longer have your 7490, but any help would be appreciated.


Hello! Update your OC and kexts and try the following boot-args -igfxblr OR -igfxblt
Let me know if this fix the problem.
Greetings
